"""
ATLAS v3.0 — LangGraph State Schema

This module defines the ATLASState TypedDict used across all pipeline nodes.
Each field is documented per the ATLAS Master Agent Prompt specification.
"""

from __future__ import annotations

from enum import Enum
import operator
from typing import Annotated, Any, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field


def merge_dicts(a: dict, b: dict) -> dict:
    """Reducer to merge two dictionaries."""
    return {**a, **b}


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Enums
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


class TestLayer(str, Enum):
    """The 5 test generation layers."""
    UNIT = "UNIT"
    INTEGRATION = "INTEGRATION"
    FUNCTIONAL = "FUNCTIONAL"
    PERFORMANCE = "PERFORMANCE"
    SECURITY = "SECURITY"


class Verdict(str, Enum):
    """Validation verdicts."""
    PASS = "PASS"
    RETRY = "RETRY"
    ESCALATE = "ESCALATE"


class OWASPCategory(str, Enum):
    """OWASP Top 10 (2021) categories."""
    A01 = "A01"  # Broken Access Control
    A02 = "A02"  # Cryptographic Failures
    A03 = "A03"  # Injection
    A04 = "A04"  # Insecure Design
    A05 = "A05"  # Security Misconfiguration
    A06 = "A06"  # Vulnerable Components
    A07 = "A07"  # Auth Failures
    A08 = "A08"  # Data Integrity Failures
    A09 = "A09"  # Logging & Monitoring Failures
    A10 = "A10"  # SSRF


class SecuritySeverity(str, Enum):
    """OWASP finding severity levels."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SecurityVerdict(str, Enum):
    """OWASP security test verdicts."""
    VULNERABLE = "VULNERABLE"
    SECURE = "SECURE"
    INCONCLUSIVE = "INCONCLUSIVE"


class FunctionClassification(str, Enum):
    """Function type classification (determined by M2/M4)."""
    PURE_FUNCTION = "PURE_FUNCTION"
    UTILITY_HELPER = "UTILITY_HELPER"
    API_HANDLER = "API_HANDLER"
    SERVICE_LAYER = "SERVICE_LAYER"
    DOMAIN_LOGIC = "DOMAIN_LOGIC"
    DB_ACCESSOR = "DB_ACCESSOR"
    CACHE_LAYER = "CACHE_LAYER"
    WORKFLOW_ORCHESTRATOR = "WORKFLOW_ORCHESTRATOR"
    AUTH_HANDLER = "AUTH_HANDLER"
    DATA_PROCESSOR = "DATA_PROCESSOR"
    SERIALIZER = "SERIALIZER"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Pydantic Models (for validated sub-structures)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


class ProjectContext(BaseModel):
    """Project-level metadata detected by M1."""
    project_name: str
    language: str  # "python", "typescript", "javascript", "java", "go"
    framework: str | None = None  # "fastapi", "express", "spring", etc.
    test_framework: str  # "pytest", "jest", "vitest", "junit5"
    conventions: dict[str, Any] = Field(default_factory=dict)
    performance_budgets: dict[str, float] | None = None  # p95 budgets if configured


class ModuleContext(BaseModel):
    """Module-level metadata from M2 AST parser."""
    module_path: str
    imports: list[str] = Field(default_factory=list)
    exports: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    dependency_tags: list[str] = Field(default_factory=list)  # ["neon", "db", "auth", ...]
    has_neon_imports: bool = False
    vulnerable_imports: list[dict[str, str]] = Field(default_factory=list)  # OWASP A06


class FunctionTarget(BaseModel):
    """Per-function analysis from M2/M4."""
    id: str  # Unique identifier: "module.function_name"
    name: str
    module_path: str
    source_code: str
    signature: str
    parameters: list[dict[str, Any]] = Field(default_factory=list)
    return_type: str | None = None
    decorators: list[str] = Field(default_factory=list)
    classification: FunctionClassification = FunctionClassification.PURE_FUNCTION
    cyclomatic_complexity: int = 1
    dependencies: list[str] = Field(default_factory=list)
    active_layers: list[TestLayer] = Field(default_factory=list)
    is_async: bool = False
    accepts_user_input: bool = False
    performs_auth: bool = False
    accesses_db: bool = False
    handles_files: bool = False
    calls_external: bool = False


class TestPlan(BaseModel):
    """Test plan generated by M4."""
    targets: list[FunctionTarget] = Field(default_factory=list)
    total_functions: int = 0
    total_layer_dispatches: int = 0  # sum of all active_layers across targets


class CoverageIntent(BaseModel):
    """Coverage metadata for a generated test suite."""
    layer_target: str
    branches_covered: list[str] = Field(default_factory=list)
    owasp_categories: list[str] = Field(default_factory=list)  # SECURITY layer only
    perf_budgets: dict[str, float] = Field(default_factory=dict)  # PERFORMANCE layer only
    known_gaps: list[str] = Field(default_factory=list)


class MockRequired(BaseModel):
    """A mock/fixture required by a test."""
    module: str
    mock_type: str  # "jest.mock", "unittest.mock", "pytest.fixture", etc.
    from_registry: bool = False
    fixture_key: str | None = None


class TestOutput(BaseModel):
    """Structured output from a layer agent (M5-*)."""
    target_file: str
    active_layer: TestLayer
    file_path: str
    framework: str
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    history_used: str = "none"
    fixtures_reused: list[str] = Field(default_factory=list)
    fixtures_registered: list[str] = Field(default_factory=list)
    coverage_intent: CoverageIntent | None = None
    mocks_required: list[MockRequired] = Field(default_factory=list)
    test_code: str
    quality_flags: list[str] = Field(default_factory=list)


class SecurityFinding(BaseModel):
    """An OWASP security finding from M5-OWASP."""
    target_file: str
    function_name: str
    owasp_category: OWASPCategory
    severity: SecuritySeverity
    test_name: str
    test_code_snippet: str
    verdict: SecurityVerdict


class TestFileWrite(BaseModel):
    """Payload for writing the generated test to disk (M7)."""
    file_path: str
    content: str


class RejectionFeedback(BaseModel):
    """Feedback from M6 validator on a failed test."""
    layer: TestLayer
    target_file: str
    failures: list[dict[str, str]] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ATLASState — The LangGraph State TypedDict
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


class ATLASState(TypedDict, total=False):
    """
    The core state schema for the ATLAS LangGraph pipeline.

    This state flows through every node. Each node receives it and
    returns an updated version. LangGraph checkpoints the state after
    every node execution to maintain history.
    """

    # ── Identity ──────────────────────────────────────────────────────────────
    run_id: str                          # UUID for this pipeline run
    thread_id: str                       # LangGraph checkpoint thread ID
    target_file: str                     # File being tested
    attempt: int                         # Retry count per layer (starts at 1)
    active_layer: str                    # Current layer: UNIT|INTEGRATION|FUNCTIONAL

                                         #                PERFORMANCE|SECURITY

    # ── Upstream context (M1–M4) ──────────────────────────────────────────────
    project_context: dict[str, Any]      # Language, framework, conventions
    module_context: dict[str, Any]       # Module metadata, dependencies
    target_context: dict[str, Any]       # Source code, AST
    test_plan: dict[str, Any]            # M4-generated test plan + layer assignments


    # ── Git diff context (M0) ────────────────────────────────────────────────
    changed_files: list[str]             # Files changed in git diff
    diff_hunks: list[dict[str, Any]]     # Function-level diff details

    # ── Fan-out results (populated by parallel agents and merged) ─────────────
    layer_outputs: Annotated[dict[str, dict[str, Any]], merge_dicts]
    disk_writes_queue: Annotated[list[dict[str, Any]], operator.add]


    # ── Your output fields ────────────────────────────────────────────────────
    reasoning: str
    test_output: dict[str, Any]          # This layer's structured JSON output
    verdict: str                         # "PASS" | "RETRY" | "ESCALATE"

    # ── OWASP overlay (populated by M5-OWASP after JOIN) ─────────────────────
    owasp_output: dict[str, Any] | None
    security_findings: list[dict[str, Any]]

    # ── Feedback loop ─────────────────────────────────────────────────────────
    rejection_feedback: dict[str, Any] | None
    
    # ── Agentic Execution (new) ───────────────────────────────────────────────
    messages: Annotated[list[BaseMessage], add_messages]
    execution_result: dict[str, Any] | None
    retry_count: int
    max_retries: int
    selected_layers: list[str]
    current_layer_index: int
    execution_queue: list[dict[str, Any]]

    # ── Disk write payload (you populate; M7 executes) ────────────────────────
    disk_write: dict[str, Any]


    # ── Coverage results (M8) ────────────────────────────────────────────────
    coverage_results: dict[str, Any] | None

    # ── Error tracking ───────────────────────────────────────────────────────
    errors: list[str]
